services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easy-uni
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:80"

volumes:
  postgres-db:
